{% set name = "nevergrad" %}
{% set version = "0.4.2.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47dfbee0d96e6e4b768338269fe8f3e48bb5f20df7712e3356694af9bb8d331a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - bayesian-optimization >=1.1.0
    - cma >=2.6.0
    - numpy >=1.15.0
    - pandas >=0.23.4
    - typing_extensions >=3.6.6
    - gym
    - pytorch
    - requests
    - matplotlib-base
    - Pillow
    - pyproj

test:
  imports:
    - nevergrad
    - nevergrad.benchmark
    - nevergrad.common
    - nevergrad.functions
    - nevergrad.functions.arcoating
    - nevergrad.functions.games
    - nevergrad.functions.mlda
    - nevergrad.functions.multiobjective
    - nevergrad.functions.photonics
    - nevergrad.functions.powersystems
    - nevergrad.functions.rl
    - nevergrad.functions.stsp
    - nevergrad.optimization
    - nevergrad.parametrization

about:
  home: https://github.com/facebookresearch/nevergrad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python toolbox for performing gradient-free optimization
  doc_url: https://facebookresearch.github.io/nevergrad/
  dev_url: https://github.com/facebookresearch/nevergrad

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
