{% set name = "nevergrad" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c908bd02c82988170ab79035459964539d69690354034fb1929dfd4213ae94ae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - bayesian-optimization >=1.2.0
    - cma >=2.6.0
    - numpy >=1.24.0
    - pandas >=1.0
    - typing_extensions >=3.6.6
    - pybobyqa >=1.2 # optional dependency but small package, can keep it for now
    - nlopt # optional dependency but small package
    # - ax-platform # optional and way too large to include by default

test:
  imports:
    - nevergrad
    - nevergrad.common
    - nevergrad.functions
    - nevergrad.ops
    - nevergrad.optimization
    - nevergrad.parametrization

about:
  home: https://github.com/facebookresearch/nevergrad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python toolbox for performing gradient-free optimization
  doc_url: https://facebookresearch.github.io/nevergrad/
  dev_url: https://github.com/facebookresearch/nevergrad

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - aldanor
    - traversaro
